//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// $Log:$
//
// DESCRIPTION:
//	DOOM main program (D_DoomMain) and game loop (D_DoomLoop),
//	plus functions to determine game mode (shareware, registered),
//	parse command line parameters, configure game parameters (turbo),
//	and call the startup functions.
//
//-----------------------------------------------------------------------------

#define	BGCOLOR		7
#define	FGCOLOR		8

#include <stdint.h>


#ifdef NORMALUNIX
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#endif


#include "doomdef.h"
#include "doomstat.h"

#include "dstrings.h"
#include "sounds.h"


#include "z_zone.h"
#include "w_wad.h"
#include "s_sound.h"
#include "v_video.h"

#include "f_finale.h"
#include "f_wipe.h"

#include "m_argv.h"
#include "m_misc.h"
#include "m_menu.h"

#include "i_system.h"
#include "i_sound.h"
#include "i_video.h"

#include "g_game.h"

#include "hu_stuff.h"
#include "wi_stuff.h"
#include "st_stuff.h"
#include "am_map.h"

#include "p_setup.h"
#include "r_local.h"

#include "d_main.h"

#include "x_mapinfo.h"
#include "hooks.h"

//
// D-DoomLoop()
// Not a globally visible function,
//  just included for source reference,
//  called by D_DoomMain, never exits.
// Manages timing and IO,
//  calls all ?_Responder, ?_Ticker, and ?_Drawer,
//  calls I_GetTime, I_StartFrame, and I_StartTic
//
void D_DoomLoop (void);


char*		wadfiles[MAXWADFILES];


boolean         nomonsters;	// checkparm of -nomonsters
boolean         respawnparm;	// checkparm of -respawn
boolean         fastparm;	// checkparm of -fast
boolean         pistolstart;	// checkparm of -pistolstart
boolean         spthings; // checkparm of -spthings

boolean         drone;

boolean		singletics = false; // debug flag to cancel adaptiveness



//extern int soundVolume;
//extern  int	sfxVolume;
//extern  int	musicVolume;

extern  boolean	inhelpscreens;

skill_t		startskill;
int             startepisode;
int		startmap;
boolean		autostart;

FILE*		debugfile;

boolean		advancedemo;

char *game_title = "DOOM";
char *window_title = "DOOM";
boolean verbose = false;
boolean nomusic = false;


char		wadfile[1024];		// primary wad file
char		mapdir[1024];           // directory of development maps


void D_CheckNetGame (void);
void D_ProcessEvents (void);
void D_DoAdvanceDemo (void);

void D_WartHack(int e, int m);
void D_CheckForFakes(void);
void D_PrintStartup(char *title, char *custom_startup);
void P_SetTimeLimit(int count);
void D_PrintHelp(void);


//
// EVENT HANDLING
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//
event_t         events[MAXEVENTS];
int             eventhead;
int 		eventtail;


//
// D_PostEvent
// Called by the I/O functions when input is detected
//
void D_PostEvent (event_t* ev)
{
    events[eventhead++] = *ev;
    eventhead = (eventhead)&(MAXEVENTS-1);
}


//
// D_ProcessEvents
// Send all the events of the given timestamp down the responder chain
//
void D_ProcessEvents (void)
{
    event_t*	ev;
	
    // IF STORE DEMO, DO NOT ACCEPT INPUT
    if ( ( gamemode == commercial )
	 && (W_CheckNumForName("map01")<0) )
      return;
	
    for ( ; eventtail != eventhead ; eventtail = (eventtail)&(MAXEVENTS-1) )
    {
	ev = &events[eventtail++];
	X_OnEvent(ev->type, ev->data1, ev->data2, ev->data3);
	if (M_Responder (ev))
	    continue;               // menu ate the event
	G_Responder (ev);
    }
}




//
// D_Display
//  draw current display, possibly wiping it from the previous
//

// wipegamestate can be set to -1 to force a wipe on the next draw
gamestate_t     wipegamestate = GS_DEMOSCREEN;
extern  boolean setsizeneeded;
extern  int             showMessages;
void R_ExecuteSetViewSize (void);
extern int netgame_prevtime;

void D_Display (void)
{
    static  boolean		viewactivestate = false;
    static  boolean		menuactivestate = false;
    static  boolean		inhelpscreensstate = false;
    static  boolean		fullscreen = false;
    static  gamestate_t		oldgamestate = -1;
    static  int			borderdrawcount;
    int				nowtime;
    int				tics;
    int				wipestart;
    int				y;
    boolean			done;
    boolean			wipe;
    boolean			redrawsbar;

    if (nodrawers)
	return;                    // for comparative timing / profiling
		
    redrawsbar = false;
    
    // change the view size if needed
    if (setsizeneeded)
    {
	R_ExecuteSetViewSize ();
	oldgamestate = -1;                      // force background redraw
	borderdrawcount = 3;
    }

    // save the current screen if about to wipe
    if (gamestate != wipegamestate)
    {
	wipe = true;
	wipe_StartScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
    }
    else
	wipe = false;

    if (gamestate == GS_LEVEL && gametic)
	HU_Erase();
    
    // do buffered drawing
    switch (gamestate)
    {
      case GS_LEVEL:
	if (!gametic)
	    break;
	if (automapactive)
	    AM_Drawer ();
	if (wipe || (viewheight != 200 && fullscreen) )
	    redrawsbar = true;
	if (inhelpscreensstate && !inhelpscreens)
	    redrawsbar = true;              // just put away the help screen
	ST_Drawer (viewheight == 200, redrawsbar );
	fullscreen = viewheight == 200;
	break;

      case GS_INTERMISSION:
	WI_Drawer ();
	break;

      case GS_FINALE:
	F_Drawer ();
	break;

      case GS_DEMOSCREEN:
	D_PageDrawer ();
	break;
    }
    
    // draw buffered stuff to screen
    I_UpdateNoBlit ();
    
    // draw the view directly
    if (gamestate == GS_LEVEL && !automapactive && gametic) {
        player_t *player = &players[displayplayer];
        if (X_AlternateRender) {
            struct canvas cv = {screens[0], viewwindowx, viewwidth, viewwindowy, viewheight};
            struct viewpoint vp = R_SetupViewpoint(player);
            X_AlternateRender(cv, vp);
        }
        else {
            R_RenderPlayerView (player);
        }
    }

    if (gamestate == GS_LEVEL && gametic)
	HU_Drawer ();
    
    // clean up border stuff
    if (gamestate != oldgamestate && gamestate != GS_LEVEL)
	I_SetPalette (W_CacheLumpName ("PLAYPAL",PU_CACHE));

    // see if the border needs to be initially drawn
    if (gamestate == GS_LEVEL && oldgamestate != GS_LEVEL)
    {
	viewactivestate = false;        // view was not active
	R_FillBackScreen ();    // draw the pattern into the back screen
    }

    // see if the border needs to be updated to the screen
    if (gamestate == GS_LEVEL && !automapactive && scaledviewwidth != 320)
    {
	if (menuactive || menuactivestate || !viewactivestate)
	    borderdrawcount = 3;
	if (borderdrawcount)
	{
	    R_DrawViewBorder ();    // erase old menu stuff
	    borderdrawcount--;
	}

    }

    menuactivestate = menuactive;
    viewactivestate = viewactive;
    inhelpscreensstate = inhelpscreens;
    oldgamestate = wipegamestate = gamestate;
    
    // draw pause pic
    if (paused)
    {
	if (automapactive)
	    y = 4;
	else
	    y = viewwindowy+4;
	V_DrawPatchDirect(viewwindowx+(scaledviewwidth-68)/2,
			  y,0,W_CacheLumpName ("M_PAUSE", PU_CACHE));
    }


    // menus go directly to the screen
    M_Drawer ();          // menu is drawn even on top of everything


    // normal update
    if (!wipe)
    {
	I_FinishUpdate ();              // page flip or blit buffer
	return;
    }
    
    // wipe update
    wipe_EndScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);

    wipestart = I_GetTime () - 1;

    do
    {
	do
	{
	    nowtime = I_GetTime ();
	    tics = nowtime - wipestart;
	} while (!tics);
	wipestart = nowtime;
	done = wipe_ScreenWipe(wipe_Melt
			       , 0, 0, SCREENWIDTH, SCREENHEIGHT, tics);
	I_UpdateNoBlit ();
	M_Drawer ();                            // menu is drawn even on top of wipes
	I_FinishUpdate ();                      // page flip or blit buffer
    } while (!done);

    // fix netgame's clock state so we don't do 40 gametics suddenly
    netgame_prevtime = I_GetTime() / ticdup;

}



//
//  D_DoomLoop
//
extern  boolean         demorecording;

void D_DoomLoop (void)
{
    if (demorecording)
	G_BeginRecording ();
		
    if (M_CheckParm ("-debugfile"))
    {
	char    filename[20];
	sprintf (filename,"debug%i.txt",consoleplayer);
	printf ("debug output to: %s\n",filename);
	debugfile = fopen (filename,"w");
    }
	
    I_InitGraphics (window_title==NULL ? game_title : window_title);

    if (timingdemo)
        TimeCore();
    else
        NetgameCore();
}



//
//  DEMO LOOP
//
int             demosequence;
int             pagetic;
char                    *pagename;


//
// D_PageTicker
// Handles timing for warped projection
//
void D_PageTicker (void)
{
    if (--pagetic < 0)
	D_AdvanceDemo ();
}



//
// D_PageDrawer
//
void D_PageDrawer (void)
{
    V_DrawPatch (0,0, 0, W_CacheLumpName(pagename, PU_CACHE));
}


//
// D_AdvanceDemo
// Called after each demo or intro demosequence finishes
//
void D_AdvanceDemo (void)
{
    advancedemo = true;
}


//
// This cycles through the demo sequences.
// FIXME - version dependend demo numbers?
//
 void D_DoAdvanceDemo (void)
{
    players[consoleplayer].playerstate = PST_LIVE;  // not reborn
    advancedemo = false;
    usergame = false;               // no save / end game here
    paused = false;
    gameaction = ga_nothing;

    if ( gamemode == retail )
      demosequence = (demosequence+1)%7;
    else
      demosequence = (demosequence+1)%6;
    
    switch (demosequence)
    {
      case 0:
	if ( gamemode == commercial )
	    pagetic = 35 * 11;
	else
	    pagetic = 170;
	gamestate = GS_DEMOSCREEN;
	pagename = "TITLEPIC";
	if ( gamemode == commercial )
	  S_ChangeMusicTo(DOOM2_TITLE, 0);
	else
	  S_ChangeMusicTo(DOOM1_TITLE, 0);
	break;
      case 1:
	G_DeferedPlayDemo ("demo1");
	break;
      case 2:
	pagetic = 200;
	gamestate = GS_DEMOSCREEN;
	pagename = "CREDIT";
	break;
      case 3:
	G_DeferedPlayDemo ("demo2");
	break;
      case 4:
	gamestate = GS_DEMOSCREEN;
	if ( gamemode == commercial)
	{
	    pagetic = 35 * 11;
	    pagename = "TITLEPIC";
	    S_ChangeMusicTo(DOOM2_TITLE, 0);
	}
	else
	{
	    pagetic = 200;

	    if ( gamemode == retail )
	      pagename = "CREDIT";
	    else
	      pagename = "HELP2";
	}
	break;
      case 5:
	G_DeferedPlayDemo ("demo3");
	break;
        // THE DEFINITIVE DOOM Special Edition demo
      case 6:
	G_DeferedPlayDemo ("demo4");
	break;
    }
}



//
// D_StartTitle
//
void D_StartTitle (void)
{
    gameaction = ga_nothing;
    demosequence = -1;
    D_AdvanceDemo ();
}




//      print title for every printed line
char            title[128];



//
// D_AddFile
//
void D_AddFile (char *file)
{
    int     numwadfiles;
    char    *newfile;
	
    for (numwadfiles = 0 ; wadfiles[numwadfiles] ; numwadfiles++)
	;

    newfile = malloc (strlen(file)+1);
    strcpy (newfile, file);
	
    wadfiles[numwadfiles] = newfile;
}

struct iwad {
    char *filename;
    int mode;
    int mission;
    int language;
    char *title;
    char *window_title;
};

struct iwad known_iwads[] = {
    {"doom2f.wad",    commercial, doom2,     french,  "DOOM 2: Hell on Earth", "DOOM II"},
    {"doom2.wad",     commercial, doom2,     english, "DOOM 2: Hell on Earth", "DOOM II"},
    {"plutonia.wad",  commercial, pack_plut, english, "DOOM 2: The Plutonia Experiment", "Final DOOM - The Plutonia Experiment"},
    {"tnt.wad",       commercial, pack_tnt,  english, "DOOM 2: TNT - Evilution", "Final DOOM - TNT: Evilution"},
    {"doomu.wad",     retail,     doom,      english, "Ultimate DOOM"},
    {"doom.wad",      registered, doom,      english, "DOOM"},
    {"doom1.wad",     shareware,  doom,      english, "DOOM", "DOOM - Shareware"},
    {"freedoom1.wad", retail,     doom,      english, "FreeDOOM: Phase 1", "FreeDOOM"},
    {"freedoom2.wad", commercial, doom2,     english, "FreeDOOM: Phase 2", "FreeDOOM"},
    {"CHEX.WAD",      retail,     doom,      english, "CHEX QUEST"},
    {NULL, 0, 0, 0, NULL}
};

bool TryIWAD(struct iwad *info) {
    bool got_it = false;
    char *doomwaddir = GetDoomWadDir();
    char *path = malloc(strlen(doomwaddir)+1+strlen(info->filename)+1);
    sprintf(path, "%s/%s", doomwaddir, info->filename);
    if ( !access (path,R_OK) ) {
        got_it = true;
        gamemode = info->mode;
        gamemission = info->mission;
        game_title = info->title;
        window_title = info->window_title;
        if (verbose && info->language == french) printf("French version\n");
        language = info->language;
        D_AddFile (path);
    }
    free(path);
    return got_it;
}



//
// IdentifyVersion
// Checks availability of IWAD files by name,
// to determine whether registered/commercial features
// should be executed (notably loading PWAD's).
//
void IdentifyVersion (void)
{

    int p = M_CheckParm("-iwad"); // only try named iwad
    char *chosen_iwad = p && p < myargc-1 ? myargv[p+1] : NULL;

    for (struct iwad *info = known_iwads; info->filename; info++) {
        if (chosen_iwad && strcmp(info->filename, chosen_iwad) != 0) continue;
        if (strcmp(info->filename, "CHEX.WAD") == 0 && !M_CheckParm("-chex")) continue;
        if (TryIWAD(info)) return;
    }

    if (verbose) printf("Game mode indeterminate.\n");
    gamemode = indetermined;
    gamemission = none;
    game_title = "Public DOOM";
    window_title = "DOOM";

    // We don't abort. Let's see what the PWAD contains.
    //exit(1);
    //I_Error ("Game mode indeterminate\n");
}


//
// D_DoomMain
//
void D_DoomMain (void)
{

    int val1, val2;
    char                    file[256];

    if (M_CheckParm("--help") || M_CheckParm("-help") || M_CheckParm("-h")) {
        D_PrintHelp();
        return;
    }

    setbuf (stdout, NULL);

    /* many command line args, but not all, processed here */

    verbose = M_CheckParm("-verbose") || M_CheckParm("-v") || M_CheckParm("--verbose");
    nomusic = M_CheckParm("-nomusic");

    IdentifyVersion ();

    nomonsters = M_CheckParm("-nomonsters");
    respawnparm = M_CheckParm("-respawn");
    fastparm = M_CheckParm("-fast");
    pistolstart = M_CheckParm("-pistolstart");
    deathmatch = M_CheckParm("-deathmatch") ? 1 : M_CheckParm ("-altdeath") ? 2 : 0;
    spthings = M_CheckParm("-spthings");

    int scale = M_GetParmInt("-turbo"); if (scale) G_SetTurbo(scale);
    int count = M_GetParmInts("-wart", &val1, &val2); if (count >= 1) D_WartHack(val1, val2);

    int time = M_GetParmInt("-timer");
    if (time && deathmatch) {
        printf("Levels will end after %d minute%s\n", time, time != 1 ? "s" : "");
        P_SetTimeLimit(time);
    }

    if ( M_CheckParm ("-avg") && deathmatch) {
        printf("Austin Virtual Gaming: Levels will end after 20 minutes\n");
        P_SetTimeLimit(20);
    }

    // get skill / episode / map from parms
    startskill = sk_medium;
    startepisode = 1;
    startmap = 1;
    autostart = false;

    int sk = M_GetParmInt("-skill");
    if (sk) {
        startskill = sk - 1;
        if (startskill < 0) startskill = 0;
        if (startskill > 4) startskill = 4;
        autostart = true;
    }

    int ep = M_GetParmInt("-episode");
    if (ep && gamemission == doom) {
        startepisode = ep;
        startmap = 1;
        autostart = true;
    }

    count = M_GetParmInts("-warp", &val1, &val2);
    if (count == 2 && gamemission == doom) {
        startepisode = val1;
        startmap = val2;
        autostart = true;
    }
    if (count == 1 && gamemission != doom) {
        startmap = val1;
        autostart = true;
    }


    // setup a normal demo or time demo (fast demo)
    char *name1 = M_GetParm("-playdemo");
    char *name2 = M_GetParm("-timedemo");
    char *name = name1 ? name1 : name2;
    if (name) {
        sprintf(file,"%s.lmp", name);
        D_AddFile(file);
        printf("Playing demo %s.lmp.\n", name);
    }


    // D_AddFile for each PWAD file mentioned after -file
    char **args = M_GetParmArgs("-file", &count);
    if (args) {
        if (gamemode == shareware) I_Error("You cannot -file with the shareware version. Register!");
        for (int i = 0; i < count; i++) D_AddFile(args[i]);
    }


    // init subsystems
    if (verbose) printf ("V_Init: allocate screens.\n");
    V_Init ();

    if (verbose) printf ("M_LoadDefaults: Load system defaults.\n");
    M_LoadDefaults ();              // load before initing other systems

    if (verbose) printf ("Z_Init: Init zone memory allocation daemon. \n");
    Z_Init ();

    if (verbose) printf ("W_Init: Init WADfiles.\n");
    W_InitMultipleFiles (wadfiles);

    // now that wads are initialized we can check for fake retail
    if (M_CheckParm ("-file")) D_CheckForFakes();
    
    // if present, load custom strings from DEHACKED lump
    int dehacked_num = W_CheckNumForName("DEHACKED");
    if (dehacked_num >= 0) {
        if (verbose) printf("DEHACKED lump found. Loading custom strings.\n");
        char *dehacked = W_CacheLumpNum(dehacked_num, PU_CACHE);
        int len = W_LumpLength(dehacked_num);
        F_SetCustomFinale(dehacked, len);
    }

    X_InitMapinfo();

    int mapinfo_num = W_CheckNumForName("MAPINFO");
    if (mapinfo_num >= 0) {
        char *mapinfo = W_CacheLumpNum(mapinfo_num, PU_CACHE);
        int len = W_LumpLength(mapinfo_num);
        //X_LoadMapinfo(mapinfo, len);
    }

    // announce DOOM
    D_PrintStartup(game_title, F_GetString("STARTUP5"));

    if (M_CheckParm("-endoom")) I_QuitEndoom(W_CacheLumpName("ENDOOM",PU_CACHE),4000);

    if (verbose) printf ("M_Init: Init miscellaneous info.\n");
    M_Init ();

    if (verbose) printf ("R_Init: Init DOOM refresh daemon - ");
    R_Init ();

    if (verbose) printf ("\nP_Init: Init Playloop state.\n");
    P_Init ();

    if (verbose) printf ("I_Init: Setting up machine state.\n");
    I_Init ();

    if (verbose) printf ("D_CheckNetGame: Checking network game status.\n");
    D_CheckNetGame ();

    if (verbose) printf ("S_Init: Setting up sound.\n");
    S_Init (snd_SfxVolume /* *8 */, snd_MusicVolume /* *8*/ );

    if (verbose) printf ("HU_Init: Setting up heads up display.\n");
    HU_Init ();

    if (verbose) printf ("ST_Init: Init status bar.\n");
    ST_Init ();
    
    // start the apropriate game based on parms
    name = M_GetParm("-record");
    if (name) {
        G_RecordDemo(name);
        autostart = true;
    }
	
    name = M_GetParm("-playdemo");
    if (name) {
        singledemo = true;              // quit after one demo
        G_DeferedPlayDemo(name);
        D_DoomLoop ();  // never returns
    }
	
    name = M_GetParm("-timedemo");
    if (name) {
        G_TimeDemo(name);
        D_DoomLoop ();  // never returns
    }
	
    name = M_GetParm("-loadgame"); // argument usually 0 to 5 but could be a letter
    if (name) {
        sprintf(file, SAVEGAMENAME"%c.dsg", name[0]);
        G_LoadGame (file);
    }

    if ( gameaction == ga_loadgame ) {
        D_DoomLoop(); // never returns
    }
    else if (autostart || netgame) {
        G_InitNew (startskill, startepisode, startmap);
        D_DoomLoop(); // never returns
    }
    else {
        D_StartTitle (); // start up intro loop
        D_DoomLoop(); // never returns
    }
}




// convenience hack to allow -wart e m to add a wad file
// prepend a tilde to the filename so wadfile will be reloadable
void D_WartHack(int val1, int val2) {
    char file[256];

    int p = M_CheckParm("-wart");
    myargv[p][4] = 'p';     // big hack, change to -warp

    // Map name handling.
    switch (gamemode) {
        case shareware:
        case retail:
        case registered:
            if (val2 == 0) { I_Error("-wart: not enough arguments for doom 1"); }
            sprintf(file,"~"DEVMAPS"E%cM%c.wad", val1, val2);
            printf("Warping to Episode %d, Map %d.\n", val1, val2);
            break;

        case commercial:
        default:
            if (val2 != 0) { I_Error("-wart: too many arguments for doom 2"); }
            sprintf(file, "~"DEVMAPS"cdata/map%02d.wad", val1);
            printf("Warping to Map %02d.\n", val1);
            break;
    }

    D_AddFile (file);
}


void D_CheckForFakes(void) {
	// These are the lumps that will be checked in IWAD,
	// if any one is not present, execution will be aborted.
	char name[23][8]=
	{
	    "e2m1","e2m2","e2m3","e2m4","e2m5","e2m6","e2m7","e2m8","e2m9",
	    "e3m1","e3m3","e3m3","e3m4","e3m5","e3m6","e3m7","e3m8","e3m9",
	    "dphoof","bfgga0","heada1","cybra1","spida1d1"
	};
	int i;

	// Check for fake IWAD with right name,
	// but w/o all the lumps of the registered version.
	if (gamemode == registered)
	    for (i = 0;i < 23; i++)
		if (W_CheckNumForName(name[i])<0)
		    I_Error("This is not the registered version.");

        // Iff additonal PWAD files are used, print modified banner
	printf (
	    "===========================================================================\n"
	    "ATTENTION:  This version of DOOM has been modified.  If you would like to\n"
	    "get a copy of the original game, call 1-800-IDGAMES or see the readme file.\n"
	    "        You will not receive technical support for modified games.\n"
	    "                      press enter to continue\n"
	    "===========================================================================\n"
	    );
	getchar ();
}


void D_PrintStartup(char *title, char *custom_startup) {
    int a = VERSION/100;
    int b = VERSION%100;
    int column_width = 75;
    char buffer[120];

    if (custom_startup) {
        sprintf(buffer, "%s", title);
    }
    else {
        sprintf(buffer, "%s - v%d.%d", title, a, b);
    }

    int padding = (column_width - strlen(buffer)) / 2;
    for (int i = 0; i < padding; i++) printf(" ");
    printf("%s", buffer);
    for (int i = 0; i < padding; i++) printf(" ");
    printf("\n");

    if (custom_startup) {
        printf("%s\n", custom_startup);
    }
    else if (gamemode == shareware) {
        printf (
            "===========================================================================\n"
            "                                Shareware!\n"
            "===========================================================================\n"
        );
    }
    else {
        printf (
            "===========================================================================\n"
            "                 Commercial product - do not distribute!\n"
            "         Please report software piracy to the SPA: 1-800-388-PIR8\n"
            "===========================================================================\n"
        );
    }

}


void PrintHelpLine(char *pattern, char *explain) {
    printf("\t%-20s - %s\n", pattern, explain);
}

void D_PrintHelp(void) {
    void (*pr)(char *, char *) = PrintHelpLine;

    printf("WAD loading control:\n");
    pr("-iwad <filename>", "select main IWAD to load in case multiple are in the directory");
    pr("-file <file1> <file2> ...", "select PWADs to load as mods. Order matters");
    printf("\n");

    printf("Ways to start a game immediately:\n");
    pr("-skill <1-5>", "autostart game at specified skill 1=baby 5=nightmare");
    pr("-episode N", "autostart game at the beginning of episode N in doom 1");
    pr("-warp N N", "autostart game at specified episode and map in doom 1");
    pr("-warp NN", "autostart game at specified map in doom 2 e.g. -warp 08");
    pr("-net N <peer1> <peer2> ...", "attempt to start peer to peer netgame as player N using TCP/IP");
    pr("-loadgame N", "load savegame N including game settings");
    printf("\n");

    printf("These options have no effect unless the game autostarts via -skill, -episode, -warp, or -net:\n");
    pr("-nomonsters", "monsters are disabled");
    pr("-fast", "monsters are faster, either moving or shooting depending");
    pr("-respawn", "monsters respawn some time after being killed");
    pr("-deathmatch", "put a netgame into deathmatch (pvp) mode");
    pr("-altdeath", "alternate deathmatch rules: items and weapons respawn eventually");
    pr("-pistolstart", "each level begins with only a pistol and 50 rounds");
    pr("-timer N", "level ends automatically after number of minutes");
    pr("-avg", "level ends automatically after 20 minutes");
    pr("-turbo <10-400>", "player movement is scaled by a percentage e.g. 130 is 30% faster");
    printf("\n");

    printf("Graphical options:\n");
    pr("-2", "scale the window by 2x");
    pr("-3", "scale the window by 3x");
    pr("-4", "scale the window by 4x");
    pr("-5", "scale the window by 5x (exact)");
    pr("-10", "scale the window by 10x (exact)");
    pr("-fullscreen", "scale the window to fullscreen borderless");
    pr("-nodraw", "disable graphics rendering entirely");
    pr("-noblit", "skip the final blit without disabling the renderer itself");
    printf("\n");

    printf("Demo options:\n");
    pr("-playdemo <name>", "play the named demo then quit");
    pr("-timedemo <name>", "play the named demo as fast as possible then quit");
    pr("-record <name>", "start recording a demo saved to named file");
    pr("-maxdemo N", "set a maximum demo size. Ends recording when limit is reached");
    printf("\n");

    printf("Netgame options (advanced):\n");
    pr("-dup N", "divide netgame's \"sample rate\" by N to reduce bandwidth");
    pr("-extratic", "send more tics worth in a netgame packet for added redundancy");
    pr("-port", "change the port used by multiplayer doom");
    pr("-solo-net", "start a netgame by yourself for purposes");
    pr("-spthings", "don't spawn netgame-only items and monsters");
    printf("\n");

    printf("Hacks:\n");
    pr("-dumplevel <dirname>", "dump map geometry to named directory");
    printf("\n");

    printf("Miscellaneous:\n");
    pr("-verbose", "print excessive amounts of details at startup and exit");
    pr("-nomusic", "disable music entirely");
    pr("-endoom", "immediately exit and display ENDOOM");
    pr("-help", "display all command line options");
    printf("\n");
}
